### ISSUE TITLE
[WACV2024] HalluciDet: Hallucinating RGB Modality for Person Detection Through Privileged Information

### ISSUE THREAD

**Issue by heitorrapela** [CalayZhou/Multispectral-Pedestrian-Detection-Resource#10]
Hello, thanks for your resource list here! :)

Please consider adding our work Hallucidet accepted at WACV2024 as a full paper and extend the abstract at LXAI@CVPR2024.

Medeiros, Heitor Rapela, et al. "HalluciDet: Hallucinating RGB Modality for Person Detection Through Privileged Information." Proceedings of the IEEE/CVF Winter Conference on Applications of Computer Vision. 2024.

Paper: https://openaccess.thecvf.com/content/WACV2024/html/Medeiros_HalluciDet_Hallucinating_RGB_Modality_for_Person_Detection_Through_Privileged_Information_WACV_2024_paper.html

Code: https://github.com/heitorrapela/HalluciDet

**Comment by CalayZhou** [comment]
thanks for your excellent work, i have updated it in the newest version!

**Comment by heitorrapela** [comment]
Hi, @CalayZhou thanks! :)
