### ISSUE TITLE
[ARXIV2024/UnderReview] MiPa: Mixed Patch Infrared-Visible Modality Agnostic Object Detection

### ISSUE THREAD

**Issue by heitorrapela** [CalayZhou/Multispectral-Pedestrian-Detection-Resource#11]
Hello, thanks for your work! :)

Please consider adding our work MiPa: Mixed Patch Infrared-Visible Modality Agnostic Object Detection

Paper: https://arxiv.org/abs/2404.18849
Code: https://github.com/heitorrapela/MiPa

ps: The code will be updated soon, paper is under review, best.

**Comment by CalayZhou** [comment]
thanks for your excellent work, i have updated it in the newest version!

**Comment by heitorrapela** [comment]
Hi, @CalayZhou thanks for the update! :)
