### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by zhanghengdev** [CalayZhou/Multispectral-Pedestrian-Detection-Resource#2]
Do you mind adding this WACV2021 paper: **Guided Attentive Feature Fusion for Multispectral Pedestrian Detection** (https://openaccess.thecvf.com/content/WACV2021/papers/Zhang_Guided_Attentive_Feature_Fusion_for_Multispectral_Pedestrian_Detection_WACV_2021_paper.pdf) ?

**Comment by CalayZhou** [comment]
thanks for your suggestion, i have updated the list with the new paper~
